### ISSUE TITLE
Rediseño de header

### ISSUE THREAD

**Issue by ricalanis** [civica-digital/financiamiento-climatico#31]
* Poner logo de Transparencia Mexicana en el top
* Título de "Financiamiento internacional para cambio climático en México"
* Dejar un párrafo informativo (el primero), y un botón que diga, "Ver más..." y abra un collapse con toda la información restante

**Comment by juanpabloe** [comment]
- [ ] Poner logo de TM en el top
- [ ] Quitar texto del header que está a la derecha
- [ ] Tipografía del título "Financiamiento etc.. etc.." es Lato
