### ISSUE TITLE
Modificación de textos

### ISSUE THREAD

**Issue by juanpabloe** [civica-digital/financiamiento-climatico#35]
- [x] Header del body
h1 Financiamiento climático en México
h2 Plataforma para la identificación de los recursos destinados a la atención del cambio climático en el país.

- [x] Texto del footer
Los datos reflejados en el mapa y los proyectos identificados son producto de un trabajo de sistematización de Transparencia Mexicana (datos 2009 – 2012) y del Centro Mexicano de Derecho Ambiental (datos 2013 – 2014). Los datos fueron obtenidos con base en la información pública disponible de fondos internacionales, agencias de cooperación, bancos multilaterales, regionales y otros actores que forman parte del financiamiento climático en México.

**Comment by jimenezjrs** [comment]
@juanpabloe el header 2 va abajo del header 1?
