### ISSUE TITLE
Fecha de última actualización de datos debajo del mapa

### ISSUE THREAD

**Issue by juanpabloe** [civica-digital/financiamiento-climatico#36]
Incluir una pequeña leyenda debajo de los KPIs del mapa (tamaño 9 o algo pequeño) que marque la última fecha de actualización.

Para dejarlo programático podríamos preguntar a Datamx.io en el dataset la última fecha de actualización

**Comment by jimenezjrs** [comment]
@juanpabloe no es posible consultarlo programáticamente. Heroku está en https y datamx en http, los browsers nuevos pueden bloquear esas peticiones, por eso aún no se puede hacer programáticamente a menos que estuviera en un sitio con http únicamente.

https://developer.mozilla.org/es/docs/Seguridad/MixedContent/arreglar_web_con_contenido_mixto
