### ISSUE TITLE
En listado de proyectos, con múltiples estados el texto se empalma

### ISSUE THREAD

**Issue by juanpabloe** [civica-digital/financiamiento-climatico#39]
![screen shot 2015-03-20 at 11 07 00 am](https://cloud.githubusercontent.com/assets/542209/6756712/56b68922-cef1-11e4-8726-a8414b5827ef.png)

**Comment by juanpabloe** [comment]
@jimenezjrs este sigue sucediendo, si hay oportunidad hay que ver como lo corregimos

**Comment by paulinabustos** [comment]
Este issue ya no se reproduce, @jimenezjrs ¿tu lo corregiste en algún PR?
